model:
  name: deposit_hold_xgb
  version: 1

  target: "label"

  columns:
    categorical:
      - merchant_category
      - channel
      - geo_bucket
      - device_type
      # ...
    numeric:
      - avg_balance_30d
      - tx_count_7d
      - tx_amt_7d
      - customer_tenure_months
      # ...
    hit_type: "hit_type"

  masking:
    # used by apply_conditional_mask via build_conditional_mask_step
    allowed_hit_types:
      - AUTH
      - PRESENTMENT
      - INTERNAL_TRANSFER
      # ...
    mask_value: "__MASKED__"

  preprocessing:
    ohe:
      # make_ohe/build_ohe_pipeline use these
      sparse: false
      dtype: "float32"
    numeric_dtype: "float32"   # docs; enforcement happens in train script

  algorithm:
    type: "xgboost.XGBClassifier"
    params:
      n_estimators: 300
      learning_rate: 0.05
      max_depth: 4
      subsample: 0.8
      colsample_bytree: 0.8
      reg_lambda: 2.0
      objective: "binary:logistic"
      tree_method: "hist"
      n_jobs: -1
      random_state: 42
      eval_metric: "logloss"

  export:
    model_dir: "models/deposit_hold_xgb"
    model_name: "deposit_hold_xgb_v1"
    save_joblib: true
    save_onnx: true

  # Optional documentation / metadata
  evaluation:
    train_window:
      start_date: "2023-01-01"
      end_date: "2024-06-30"
    oot_window:
      start_date: "2024-07-01"
      end_date: "2024-09-30"
    performance:
      auc_train: 0.94
      auc_oot: 0.92
      cutoff_strategy:
        description: "Top 2% highest risk scores"
        cutoff_score: 0.87
