name: Checkout repository
description: "Action to clone and checks out the repository."
inputs:
  github_token:
    description: "GitHub token used for authentication"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Git configs
      env: 
        USERNAME: ${{ github.actor }}
      run: |
        git config --global user.name $USERNAME
        git config --global user.email "github-actions@github.com"
        git config --global --add safe.directory $GITHUB_WORKSPACE

    - name: Initialize repository and fetch code
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        GITHUB_SERVER_URL: ${{ env.GITHUB_SERVER_URL }}
        GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }}
        GITHUB_REF: ${{ env.GITHUB_REF }}
      run: |
        git init
        git remote add origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        git fetch --depth=1 origin $GITHUB_REF
        git checkout FETCH_HEAD
