name: Generate Next RC Tag

on:
  workflow_dispatch:  # Manual trigger

jobs:
  get-next-rc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for tag history

      - name: Get latest base tag from main
        id: get_base_tag
        run: |
          git fetch origin main --tags
          BASE_TAG=$(git tag --merged origin/main | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n1)

          if [[ -z "$BASE_TAG" ]]; then
            BASE_TAG="v0.1.0"
            echo "No base tag found. Defaulting to $BASE_TAG"
          fi

          echo "base=$BASE_TAG" >> $GITHUB_OUTPUT

      - name: Generate next RC tag
        id: get_next_rc
        run: |
          BASE=${{ steps.get_base_tag.outputs.base }}
          git fetch --tags

          LATEST_RC=$(git tag --list "${BASE}rc*" | sort -V | tail -n1)

          if [[ -z "$LATEST_RC" ]]; then
            NEXT_TAG="${BASE}rc1"
          else
            RC_NUM=$(echo "$LATEST_RC" | sed -E "s/^${BASE}rc([0-9]+)$/\1/")
            NEXT_RC_NUM=$((RC_NUM + 1))
            NEXT_TAG="${BASE}rc${NEXT_RC_NUM}"
          fi

          echo "Next RC tag: $NEXT_TAG"
          echo "tag=$NEXT_TAG" >> $GITHUB_OUTPUT

      - name: Output result
        run: echo "Generated RC tag: ${{ steps.get_next_rc.outputs.tag }}"
