name: Use HashiCorp Secrets with Separate Jobs

on:
  push:
    branches:
      - main

jobs:
  fetch-secrets:
    runs-on: ubuntu-latest
    outputs:
      a_password: ${{ steps.fetch-secrets.outputs.A_PASSWORD }}
      a_api_token: ${{ steps.fetch-secrets.outputs.A_API_TOKEN }}
    steps:
      # Step 1: Fetch secrets from HashiCorp Vault
      - name: Fetch secrets from Vault
        id: fetch-secrets
        uses: hashicorp/get-secrets-action@v2.5
        with:
          method: jwt
          path: examplepath
          role: example-role
          jwt: ${{ secrets.JWT_TOKEN }}
          namespace: some_namespace
          secrets: |
            kv/data/sharedsecrets artifactoryname | A_PASSWORD
            kv/data/example a_api_token | A_API_TOKEN

  use-secrets:
    runs-on: ubuntu-latest
    needs: fetch-secrets
    steps:
      # Step 1: Use secrets in a job with the old Docker image
      - name: Run with old Docker image
        uses: docker://your-old-image:tag
        env:
          A_PASSWORD: ${{ needs.fetch-secrets.outputs.a_password }}
          A_API_TOKEN: ${{ needs.fetch-secrets.outputs.a_api_token }}
        with:
          args: your-command
