name: Pass Secrets Between Jobs

on:
  push:
    branches:
      - main

jobs:
  fetch-secrets:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Fetch secrets using HashiCorp Vault action
      - name: Fetch secrets from HashiCorp Vault
        id: fetch-secrets
        uses: hashicorp/get-secrets-action@v2.5
        with:
          url: https://vault.yourdomain.com
          namespace: your-namespace
          secrets: |
            secret1:path/to/secret1
            secret2:path/to/secret2
          token: ${{ secrets.VAULT_TOKEN }}

      # Step 2: Set secrets as outputs using environment files
      - name: Set secrets as outputs
        run: |
          echo "secret1=${{ steps.fetch-secrets.outputs.secret1 }}" >> $GITHUB_ENV
          echo "secret2=${{ steps.fetch-secrets.outputs.secret2 }}" >> $GITHUB_ENV

  use-old-image:
    needs: fetch-secrets
    runs-on: ubuntu-latest
    container:
      image: your-old-image:tag
    env:
      # Pass the outputs as environment variables
      SECRET_1: ${{ env.secret1 }}
      SECRET_2: ${{ env.secret2 }}

    steps:
      # Step 3: Use secrets in the containerized job
      - name: Use secrets in old image
        run: |
          echo "SECRET_1 is: $SECRET_1"
          echo "SECRET_2 is: $SECRET_2"
