name: Python Test and Coverage

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specify your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov

    - name: Run tests and coverage
      run: |
        coverage run -m pytest tests/ -vv > pytest_output.txt
        coverage report -m --fail-under=80 > coverage_output.txt

    - name: Post results to PR
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pytest_summary=$(cat pytest_output.txt)
        coverage_summary=$(cat coverage_output.txt)
        comment_body="#### PyTest Results:\n\`\`\`\n$pytest_summary\n\`\`\`\n#### Coverage Report:\n\`\`\`\n$coverage_summary\n\`\`\`"
        echo "$comment_body" > comment_body.md
        curl -s -H "Authorization: token $GITHUB_TOKEN" \
             -X POST -d "{\"body\": \"$(<comment_body.md)\"}" \
             https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments
